# Site settings
title: Smart Cities Architecture
description: "A reference framework for the development of architectures for incremental and composable Smart Cities."

baseurl: "/smartcitiesarchitecture"
rooturl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude: [node_modules, gruntfile.js, package,json]
